version: 0.0
os: linux
files:
   - source: /WebContent/LoginServlet.java
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
